//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project5.saveServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="saveServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/putStringToFile", ReplyAction="http://tempuri.org/IService1/putStringToFileResponse")]
        string putStringToFile(string username, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/putStringToFile", ReplyAction="http://tempuri.org/IService1/putStringToFileResponse")]
        System.Threading.Tasks.Task<string> putStringToFileAsync(string username, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getStringFromFile", ReplyAction="http://tempuri.org/IService1/getStringFromFileResponse")]
        string getStringFromFile(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getStringFromFile", ReplyAction="http://tempuri.org/IService1/getStringFromFileResponse")]
        System.Threading.Tasks.Task<string> getStringFromFileAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Project5.saveServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Project5.saveServiceReference.IService1>, Project5.saveServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string putStringToFile(string username, string value) {
            return base.Channel.putStringToFile(username, value);
        }
        
        public System.Threading.Tasks.Task<string> putStringToFileAsync(string username, string value) {
            return base.Channel.putStringToFileAsync(username, value);
        }
        
        public string getStringFromFile(string username) {
            return base.Channel.getStringFromFile(username);
        }
        
        public System.Threading.Tasks.Task<string> getStringFromFileAsync(string username) {
            return base.Channel.getStringFromFileAsync(username);
        }
    }
}
